<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-15S6U3P" failures="21" tests="41" name="Test1" time="380.687" errors="0" timestamp="2023-01-11T05:06:44 EST">
  <testcase classname="testLayer.AccountOverviewTest" name="AccountOverview_verifyLink" time="3.861"/>
  <testcase classname="testLayer.LoanRequestTest" name="LoanRequest_Validdata" time="5.434"/>
  <testcase classname="testLayer.LoginTest" name="Login_InvalidEmptyInput" time="2.626"/>
  <testcase classname="testLayer.LoginTest" name="Login_InvalidPassword" time="2.499">
    <failure type="java.lang.AssertionError" message="expected [The username and password could not be verified.] but found [An internal error has occurred and has been logged.]">
      <![CDATA[java.lang.AssertionError: expected [The username and password could not be verified.] but found [An internal error has occurred and has been logged.]
at testLayer.LoginTest.Login_InvalidPassword(LoginTest.java:84)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Login_InvalidPassword -->
  <testcase classname="testLayer.LoginTest" name="Login_InvalidUnregisteredIdpass" time="2.529">
    <failure type="java.lang.AssertionError" message="expected [The username and password could not be verified.] but found [An internal error has occurred and has been logged.]">
      <![CDATA[java.lang.AssertionError: expected [The username and password could not be verified.] but found [An internal error has occurred and has been logged.]
at testLayer.LoginTest.Login_InvalidUnregisteredIdpass(LoginTest.java:95)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Login_InvalidUnregisteredIdpass -->
  <testcase classname="testLayer.LoginTest" name="Login_valid" time="4.746"/>
  <testcase classname="testLayer.OpenNewAccTest" name="OpenNewAcc_CreateAcc" time="7.375"/>
  <testcase classname="testLayer.UpdateContactInfoTest" name="UpdateContactInfo_Updatedata" time="24.838">
    <failure type="org.openqa.selenium.NoSuchElementException" message="no such element: Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;link text&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;Update Contact Info&amp;quot;}
  (Session info: chrome=108.0.5359.125)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: &amp;apos;4.4.0&amp;apos;, revision: &amp;apos;e5c75ed026a&amp;apos;
System info: host: &amp;apos;DESKTOP-15S6U3P&amp;apos;, ip: &amp;apos;192.168.18.1&amp;apos;, os.name: &amp;apos;Windows 11&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;17.0.5&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [3ce63bc78740609f4ab6510ca8fdcdc5, findElement {using=link text, value=Update Contact Info}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.125, chrome: {chromedriverVersion: 107.0.5304.62 (1eec40d3a576..., userDataDir: C:\Users\khush\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:49735}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:49735/devtoo..., se:cdpVersion: 108.0.5359.125, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 3ce63bc78740609f4ab6510ca8fdcdc5">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"link text","selector":"Update Contact Info"}
  (Session info: chrome=108.0.5359.125)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'DESKTOP-15S6U3P', ip: '192.168.18.1', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [3ce63bc78740609f4ab6510ca8fdcdc5, findElement {using=link text, value=Update Contact Info}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.125, chrome: {chromedriverVersion: 107.0.5304.62 (1eec40d3a576..., userDataDir: C:\Users\khush\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:49735}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:49735/devtoo..., se:cdpVersion: 108.0.5359.125, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 3ce63bc78740609f4ab6510ca8fdcdc5
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:60)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:365)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:357)
at pomPackage.PomUpdateContactInfo.clickupdateinfolink(PomUpdateContactInfo.java:16)
at testLayer.UpdateContactInfoTest.UpdateContactInfo_Updatedata(UpdateContactInfoTest.java:86)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- UpdateContactInfo_Updatedata -->
  <testcase classname="testLayer.UpdateContactInfoTest" name="UpdateContactInfo_Verifypopulatedata" time="24.559">
    <failure type="org.openqa.selenium.NoSuchElementException" message="no such element: Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;link text&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;Update Contact Info&amp;quot;}
  (Session info: chrome=108.0.5359.125)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: &amp;apos;4.4.0&amp;apos;, revision: &amp;apos;e5c75ed026a&amp;apos;
System info: host: &amp;apos;DESKTOP-15S6U3P&amp;apos;, ip: &amp;apos;192.168.18.1&amp;apos;, os.name: &amp;apos;Windows 11&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;17.0.5&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [1efecaed0ea959935452c9a1528ca5a8, findElement {using=link text, value=Update Contact Info}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.125, chrome: {chromedriverVersion: 107.0.5304.62 (1eec40d3a576..., userDataDir: C:\Users\khush\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:49812}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:49812/devtoo..., se:cdpVersion: 108.0.5359.125, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 1efecaed0ea959935452c9a1528ca5a8">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"link text","selector":"Update Contact Info"}
  (Session info: chrome=108.0.5359.125)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'DESKTOP-15S6U3P', ip: '192.168.18.1', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [1efecaed0ea959935452c9a1528ca5a8, findElement {using=link text, value=Update Contact Info}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.125, chrome: {chromedriverVersion: 107.0.5304.62 (1eec40d3a576..., userDataDir: C:\Users\khush\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:49812}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:49812/devtoo..., se:cdpVersion: 108.0.5359.125, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 1efecaed0ea959935452c9a1528ca5a8
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:60)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:365)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:357)
at pomPackage.PomUpdateContactInfo.clickupdateinfolink(PomUpdateContactInfo.java:16)
at testLayer.UpdateContactInfoTest.UpdateContactInfo_Verifypopulatedata(UpdateContactInfoTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- UpdateContactInfo_Verifypopulatedata -->
  <testcase classname="testLayer.BillPayTest" name="BillPay_Emptyfields" time="7.731"/>
  <testcase classname="testLayer.FindTransactionsTest" name="FindTransactions_ID" time="6.357"/>
  <testcase classname="testLayer.ForgotInfoTest" name="ForgotLogin_Formvisible" time="6.605"/>
  <testcase classname="testLayer.RegisterTest" name="Register_valid" time="4.821">
    <failure type="java.lang.AssertionError" message="expected [Your account was created successfully. You are now logged in.] but found [If you have an account with us you can sign-up for free instant online access. You will have to provide some personal information.]">
      <![CDATA[java.lang.AssertionError: expected [Your account was created successfully. You are now logged in.] but found [If you have an account with us you can sign-up for free instant online access. You will have to provide some personal information.]
at testLayer.RegisterTest.Register_valid(RegisterTest.java:90)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Register_valid -->
  <testcase classname="testLayer.TransferFundsTest" name="TransferFunds_Valid" time="10.375"/>
  <testcase classname="testLayer.BillPayTest" name="BillPay_InvalidSpecialCharacter" time="8.335"/>
  <testcase classname="testLayer.FindTransactionsTest" name="FindTransactions_Date" time="6.136"/>
  <testcase classname="testLayer.ForgotInfoTest" name="ForgotLogin_Valid" time="8.085">
    <failure type="java.lang.AssertionError" message="expected [Your login information was located successfully. You are now logged in.] but found [The customer information provided could not be found.]">
      <![CDATA[java.lang.AssertionError: expected [Your login information was located successfully. You are now logged in.] but found [The customer information provided could not be found.]
at testLayer.ForgotInfoTest.ForgotLogin_Valid(ForgotInfoTest.java:72)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- ForgotLogin_Valid -->
  <testcase classname="testLayer.RegisterTest" name="Register_invalidwithNumber" time="8.034">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testLayer.RegisterTest.Register_invalidwithNumber(RegisterTest.java:113)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Register_invalidwithNumber -->
  <testcase classname="testLayer.TransferFundsTest" name="TransferFunds_InvalidToAcc" time="5.383">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testLayer.TransferFundsTest.TransferFunds_InvalidToAcc(TransferFundsTest.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- TransferFunds_InvalidToAcc -->
  <testcase classname="testLayer.BillPayTest" name="BillPay_InvalidwithNumbers" time="8.565"/>
  <testcase classname="testLayer.FindTransactionsTest" name="FindTransactions_Daterange" time="5.481"/>
  <testcase classname="testLayer.ForgotInfoTest" name="ForgotLogin_InvalidEmptyFields" time="4.811"/>
  <testcase classname="testLayer.RegisterTest" name="Register_invalidwithSpecialCharacter" time="5.108">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testLayer.RegisterTest.Register_invalidwithSpecialCharacter(RegisterTest.java:136)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Register_invalidwithSpecialCharacter -->
  <testcase classname="testLayer.TransferFundsTest" name="TransferFunds_InvalidAmount" time="0.0">
    <skipped/>
  </testcase> <!-- TransferFunds_InvalidAmount -->
  <testcase classname="testLayer.BillPayTest" name="BillPay_InvalidPinPhoneNumber" time="8.263"/>
  <testcase classname="testLayer.BillPayTest" name="BillPay_InvalidPinPhoneNumber" time="8.337"/>
  <testcase classname="testLayer.FindTransactionsTest" name="FindTransactions_Amount" time="5.378"/>
  <testcase classname="testLayer.ForgotInfoTest" name="ForgotLogin_Unregisterd" time="8.235"/>
  <testcase classname="testLayer.RegisterTest" name="Register_invalidwithSpace" time="5.159">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testLayer.RegisterTest.Register_invalidwithSpace(RegisterTest.java:159)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Register_invalidwithSpace -->
  <testcase classname="testLayer.BillPayTest" name="BillPay_InvalidAccountno" time="7.974">
    <failure type="java.lang.AssertionError" message="expected [Bill Payment to jay in the amount of $100.0 from account [[[[ChromeDriver: chrome on WINDOWS (622244e09db9e4c3b43650ba31e89d68)] -&amp;gt; css selector: #rightPanel &amp;gt; div &amp;gt; div:nth-child(1) &amp;gt; form &amp;gt; table &amp;gt; tbody &amp;gt; tr:nth-child(13) &amp;gt; td:nth-child(2) &amp;gt; select]] -&amp;gt; tag name: option] was successful.] but found []">
      <![CDATA[java.lang.AssertionError: expected [Bill Payment to jay in the amount of $100.0 from account [[[[ChromeDriver: chrome on WINDOWS (622244e09db9e4c3b43650ba31e89d68)] -> css selector: #rightPanel > div > div:nth-child(1) > form > table > tbody > tr:nth-child(13) > td:nth-child(2) > select]] -> tag name: option] was successful.] but found []
at testLayer.BillPayTest.BillPay_InvalidAccountno(BillPayTest.java:141)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- BillPay_InvalidAccountno -->
  <testcase classname="testLayer.BillPayTest" name="BillPay_InvalidAccountno" time="8.084">
    <failure type="java.lang.AssertionError" message="expected [Bill Payment to jay in the amount of $100.0 from account [[[[ChromeDriver: chrome on WINDOWS (b6263505cadde864f11e793ee96c93bc)] -&amp;gt; css selector: #rightPanel &amp;gt; div &amp;gt; div:nth-child(1) &amp;gt; form &amp;gt; table &amp;gt; tbody &amp;gt; tr:nth-child(13) &amp;gt; td:nth-child(2) &amp;gt; select]] -&amp;gt; tag name: option] was successful.] but found []">
      <![CDATA[java.lang.AssertionError: expected [Bill Payment to jay in the amount of $100.0 from account [[[[ChromeDriver: chrome on WINDOWS (b6263505cadde864f11e793ee96c93bc)] -> css selector: #rightPanel > div > div:nth-child(1) > form > table > tbody > tr:nth-child(13) > td:nth-child(2) > select]] -> tag name: option] was successful.] but found []
at testLayer.BillPayTest.BillPay_InvalidAccountno(BillPayTest.java:141)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- BillPay_InvalidAccountno -->
  <testcase classname="testLayer.BillPayTest" name="BillPay_InvalidAccountno" time="8.092">
    <failure type="java.lang.AssertionError" message="expected [Bill Payment to jay in the amount of $100.0 from account [[[[ChromeDriver: chrome on WINDOWS (6a3cd278728a17d01eaaf867d78ece99)] -&amp;gt; css selector: #rightPanel &amp;gt; div &amp;gt; div:nth-child(1) &amp;gt; form &amp;gt; table &amp;gt; tbody &amp;gt; tr:nth-child(13) &amp;gt; td:nth-child(2) &amp;gt; select]] -&amp;gt; tag name: option] was successful.] but found []">
      <![CDATA[java.lang.AssertionError: expected [Bill Payment to jay in the amount of $100.0 from account [[[[ChromeDriver: chrome on WINDOWS (6a3cd278728a17d01eaaf867d78ece99)] -> css selector: #rightPanel > div > div:nth-child(1) > form > table > tbody > tr:nth-child(13) > td:nth-child(2) > select]] -> tag name: option] was successful.] but found []
at testLayer.BillPayTest.BillPay_InvalidAccountno(BillPayTest.java:141)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- BillPay_InvalidAccountno -->
  <testcase classname="testLayer.RegisterTest" name="Register_invalidEmpty" time="5.221">
    <failure type="java.lang.AssertionError" message="Arrays differ at element [6]: Phone number is required. !=  expected [Phone number is required.] but found []">
      <![CDATA[java.lang.AssertionError: Arrays differ at element [6]: Phone number is required. !=  expected [Phone number is required.] but found []
at testLayer.RegisterTest.Register_invalidEmpty(RegisterTest.java:170)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- Register_invalidEmpty -->
  <testcase classname="testLayer.RegisterTest" name="Register_invalidPin" time="4.943">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testLayer.RegisterTest.Register_invalidPin(RegisterTest.java:189)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Register_invalidPin -->
  <testcase classname="testLayer.RegisterTest" name="Register_invalidPin" time="5.121">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testLayer.RegisterTest.Register_invalidPin(RegisterTest.java:189)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Register_invalidPin -->
  <testcase classname="testLayer.RegisterTest" name="Register_invalidPhoneno" time="4.918">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testLayer.RegisterTest.Register_invalidPhoneno(RegisterTest.java:211)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Register_invalidPhoneno -->
  <testcase classname="testLayer.RegisterTest" name="Register_invalidPhoneno" time="5.117">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testLayer.RegisterTest.Register_invalidPhoneno(RegisterTest.java:211)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Register_invalidPhoneno -->
  <testcase classname="testLayer.RegisterTest" name="Register_invalidSSn" time="4.937">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testLayer.RegisterTest.Register_invalidSSn(RegisterTest.java:233)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Register_invalidSSn -->
  <testcase classname="testLayer.RegisterTest" name="Register_invalidSSn" time="5.055">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testLayer.RegisterTest.Register_invalidSSn(RegisterTest.java:233)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Register_invalidSSn -->
  <testcase classname="testLayer.RegisterTest" name="Register_invalidSSn" time="5.008">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testLayer.RegisterTest.Register_invalidSSn(RegisterTest.java:233)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Register_invalidSSn -->
  <testcase classname="testLayer.RegisterTest" name="Register_invalidConfirmpass" time="7.083"/>
</testsuite> <!-- Test1 -->
