<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-15S6U3P" failures="1" tests="4" name="testLayer.ForgotInfoTest" time="35.433" errors="0" timestamp="2023-01-11T05:06:44 EST" skipped="0">
  <testcase classname="testLayer.ForgotInfoTest" name="ForgotLogin_Formvisible" time="8.740"/>
  <system-out/>
  <testcase classname="testLayer.ForgotInfoTest" name="ForgotLogin_Valid" time="9.953">
    <failure message="expected [Your login information was located successfully. You are now logged in.] but found [The customer information provided could not be found.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Your login information was located successfully. You are now logged in.] but found [The customer information provided could not be found.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testLayer.ForgotInfoTest.ForgotLogin_Valid(ForgotInfoTest.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- ForgotLogin_Valid -->
  <system-out/>
  <testcase classname="testLayer.ForgotInfoTest" name="ForgotLogin_InvalidEmptyFields" time="6.722"/>
  <system-out/>
  <testcase classname="testLayer.ForgotInfoTest" name="ForgotLogin_Unregisterd" time="10.018"/>
  <system-out/>
</testsuite> <!-- testLayer.ForgotInfoTest -->
